Initialize imports at level=0
In Python 3, min level of imports is 0. It fails at -1 with error:

```
ValueError: level must be >= 0
```

__builtins__ is not a dict. Hence getting and setting attributes using getattr and setattr respectively